import os
import re
import glob
import sys

indir = '/uscms_data/d2/dsperka/8TeV/Samples/29May/'
outdir = '/uscms_data/d2/dsperka/8TeV/Samples/29May_All/'

list = [
'WJets',
'W1Jets',
'W2Jets',
'W3Jets',
'W4Jets',
'TTbar_Madgraph',
'TTbar_Powheg',
'T_t',
'Tbar_t',
'T_tW',
'Tbar_tW',
'T_s',
'Tbar_s',
'WW',
'ZJets_M50',
'ZZ',
'WJets_JESUP',
'W1Jets_JESUP',
'W2Jets_JESUP',
'W3Jets_JESUP',
'W4Jets_JESUP',
'TTbar_Madgraph_JESUP',
'TTbar_Powheg_JESUP',
'T_t_JESUP',
'Tbar_t_JESUP',
'T_tW_JESUP',
'Tbar_tW_JESUP',
'T_s_JESUP',
'Tbar_s_JESUP',
'WW_JESUP',
'ZJets_M50_JESUP',
'ZZ_JESUP',
'WJets_JESDOWN',
'W1Jets_JESDOWN',
'W2Jets_JESDOWN',
'W3Jets_JESDOWN',
'W4Jets_JESDOWN',
'TTbar_Madgraph_JESDOWN',
'TTbar_Powheg_JESDOWN',
'T_t_JESDOWN',
'Tbar_t_JESDOWN',
'T_tW_JESDOWN',
'Tbar_tW_JESDOWN',
'T_s_JESDOWN',
'Tbar_s_JESDOWN',
'WW_JESDOWN',
'ZJets_M50_JESDOWN',
'ZZ_JESDOWN',
'WJets_JERUP',
'W1Jets_JERUP',
'W2Jets_JERUP',
'W3Jets_JERUP',
'W4Jets_JERUP',
'TTbar_Madgraph_JERUP',
'TTbar_Powheg_JERUP',
'T_t_JERUP',
'Tbar_t_JERUP',
'T_tW_JERUP',
'Tbar_tW_JERUP',
'T_s_JERUP',
'Tbar_s_JERUP',
'WW_JERUP',
'ZJets_M50_JERUP',
'ZZ_JERUP',
'WJets_JERDOWN',
'W1Jets_JERDOWN',
'W2Jets_JERDOWN',
'W3Jets_JERDOWN',
'W4Jets_JERDOWN',
'TTbar_Madgraph_JERDOWN',
'TTbar_Powheg_JERDOWN',
'T_t_JERDOWN',
'Tbar_t_JERDOWN',
'T_tW_JERDOWN',
'Tbar_tW_JERDOWN',
'T_s_JERDOWN',
'Tbar_s_JERDOWN',
'WW_JERDOWN',
'ZJets_M50_JERDOWN',
'ZZ_JERDOWN',
'WJets_BTAGUP',
'W1Jets_BTAGUP',
'W2Jets_BTAGUP',
'W3Jets_BTAGUP',
'W4Jets_BTAGUP',
'TTbar_Madgraph_BTAGUP',
'TTbar_Powheg_BTAGUP',
'T_t_BTAGUP',
'Tbar_t_BTAGUP',
'T_tW_BTAGUP',
'Tbar_tW_BTAGUP',
'T_s_BTAGUP',
'Tbar_s_BTAGUP',
'WW_BTAGUP',
'ZJets_M50_BTAGUP',
'ZZ_BTAGUP',
'WJets_BTAGDOWN',
'W1Jets_BTAGDOWN',
'W2Jets_BTAGDOWN',
'W3Jets_BTAGDOWN',
'W4Jets_BTAGDOWN',
'TTbar_Madgraph_BTAGDOWN',
'TTbar_Powheg_BTAGDOWN',
'T_t_BTAGDOWN',
'Tbar_t_BTAGDOWN',
'T_tW_BTAGDOWN',
'Tbar_tW_BTAGDOWN',
'T_s_BTAGDOWN',
'Tbar_s_BTAGDOWN',
'WW_BTAGDOWN',
'ZJets_M50_BTAGDOWN',
'ZZ_BTAGDOWN',
'QCD_Pt_80_170_EM',
'QCD_Pt_170_250_EM',
'QCD_Pt_250_350_EM',
'QCD_Pt_350_EM',
'QCD_Pt_80_170_EM_JESUP',
'QCD_Pt_170_250_EM_JESUP',
'QCD_Pt_250_350_EM_JESUP',
'QCD_Pt_350_EM_JESUP',
'QCD_Pt_80_170_EM_JESDOWN',
'QCD_Pt_170_250_EM_JESDOWN',
'QCD_Pt_250_350_EM_JESDOWN',
'QCD_Pt_350_EM_JESDOWN',
'QCD_Pt_80_170_EM_JERUP',
'QCD_Pt_170_250_EM_JERUP',
'QCD_Pt_250_350_EM_JERUP',
'QCD_Pt_350_EM_JERUP',
'QCD_Pt_80_170_EM_JERDOWN',
'QCD_Pt_170_250_EM_JERDOWN',
'QCD_Pt_250_350_EM_JERDOWN',
'QCD_Pt_350_EM_JERDOWN',
'QCD_Pt_80_170_EM_BTAGUP',
'QCD_Pt_170_250_EM_BTAGUP',
'QCD_Pt_250_350_EM_BTAGUP',
'QCD_Pt_350_EM_BTAGUP',
'QCD_Pt_80_170_EM_BTAGDOWN',
'QCD_Pt_170_250_EM_BTAGDOWN',
'QCD_Pt_250_350_EM_BTAGDOWN',
'QCD_Pt_350_EM_BTAGDOWN',
'TTbar_matchingdown',
'TTbar_matchingup',
'TTbar_scaledown',
'TTbar_scaleup',
#'TT_Mtt_700to1000',
#'TT_Mtt_1000toInf',
#'TT_Mtt_700to1000_JESUP',
#'TT_Mtt_1000toInf_JESUP',
#'TT_Mtt_700to1000_JESDOWN',
#'TT_Mtt_1000toInf_JESDOWN',
#'TT_Mtt_700to1000_JERUP',
#'TT_Mtt_1000toInf_JERUP',
#'TT_Mtt_700to1000_JERDOWN',
#'TT_Mtt_1000toInf_JERDOWN',
#'TT_Mtt_700to1000_BTAGUP',
#'TT_Mtt_1000toInf_BTAGUP',
#'TT_Mtt_700to1000_BTAGDOWN',
#'TT_Mtt_1000toInf_BTAGDOWN',
]


if not os.path.exists(outdir):
    os.mkdir(outdir)

j = 0
for i in list:

    indirec = indir + i

    os.system('hadd ' + outdir + i +'.root ' + indirec +'/*' +'root')
 
    j += 1
    
